name: Build GhostPointer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyautogui PyQt6
    
    - name: Build executable
      run: |
        cd src
        pyinstaller --onefile --windowed --name=GhostPointer main.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: GhostPointer
        path: src/dist/GhostPointer.exe