name: Build GhostPointer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r GhostPointer/requirements.txt
    
    - name: Build executable
      run: |
        cd GhostPointer
        pyinstaller --onefile --windowed --name=GhostPointer --add-data "assets;assets" --icon=assets/GhostPointer.ico --manifest="../GhostPointer.manifest" main.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: GhostPointer
        path: GhostPointer/dist/GhostPointer.exe